# Generated by Django 5.2.6 on 2025-09-10 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_alter_bloque_nombre_alter_categoria_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloque',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
