# Generated by Django 5.2.6 on 2025-09-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripción',
            field=models.TextField(default='', max_length=2000),
            preserve_default=False,
        ),
    ]
