# Generated by Django 5.2.6 on 2025-09-10 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_producto_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripción',
            field=models.TextField(),
        ),
    ]
